name: Checkov Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov on security-pipeline only
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/security-pipeline
          framework: terraform
          soft_fail: false

      - name: Run Checkov on vulnerable-lab (informational only)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/vulnerable-lab
          framework: terraform
          soft_fail: true
